pragma Singleton
import QtQuick

// Generated by artwork/generate_moos_design_core.py.
// Edit the generator, never this file.
QtObject {
    // Read the LOCALE, never Qt.application.layoutDirection: the latter follows
    // an installed translator, and MoOS ships bilingual QML strings instead of
    // Qt translation catalogues, so it is LeftToRight on every MoOS session
    // including Arabic ones.
    readonly property bool rtl: Qt.locale().textDirection === Qt.RightToLeft
    readonly property string language: rtl ? "ar" : "en"

    // The one string helper. An app that writes its own `local()` is free to,
    // but it must take its direction from here.
    function local(ar, en) { return rtl ? ar : en }
}
