pragma Singleton
import QtQuick

// Generated by artwork/generate_moos_design_core.py.
// Edit artwork/moos-design/tokens.json, never this file.
QtObject {
    id: core

    // spacing
    readonly property int space1: 4
    readonly property int space2: 8
    readonly property int space3: 12
    readonly property int space4: 16
    readonly property int space5: 24
    readonly property int space6: 32
    readonly property int space7: 40
    readonly property int space8: 48

    // radius
    readonly property int radiusSmall: 8
    readonly property int radiusControl: 12
    readonly property int radiusCard: 16
    readonly property int radiusPanel: 24
    readonly property int radiusDialog: 28
    readonly property int radiusPill: 999

    // target
    readonly property int targetCompact: 40
    readonly property int targetControl: 44
    readonly property int targetComfortable: 48

    // type
    readonly property int typeCaption: 11
    readonly property int typeSecondary: 13
    readonly property int typeBody: 14
    readonly property int typeLabel: 15
    readonly property int typeTitle: 20
    readonly property int typeHeadline: 24
    readonly property int typeDisplay: 32
    readonly property int typeHero: 48

    // weight
    readonly property int weightRegular: 400
    readonly property int weightMedium: 500
    readonly property int weightDemiBold: 600
    readonly property int weightBold: 700

    // motion — the designed durations, at factor 1
    readonly property int motionFastReference: 120
    readonly property int motionPressReference: 160
    readonly property int motionGeometryReference: 220
    readonly property int motionEmphasisReference: 260
    readonly property int motionPageReference: 320
    readonly property int motionPortalReference: 460

    // The one animation-speed control, reaching every MoOS surface.
    //
    // Kirigami computes Units.longDuration from [KDE] AnimationDurationFactor,
    // which moos-visual-tier writes per hardware tier and the owner can change;
    // it is 200 at factor 1 and floored to 1 with animations off. This singleton
    // must not IMPORT Kirigami — the session splash and the login greeter load it
    // in engines where that import need not resolve — so it asks for the value at
    // run time and keeps the designed speed when the answer is unavailable.
    property QtObject motionProbe: null
    readonly property int liveLongDuration: motionProbe ? motionProbe.longDuration : 200

    // motion — what surfaces read; 0 when the owner has animations off
    readonly property int motionFast: scaled(liveLongDuration, motionFastReference)
    readonly property int motionPress: scaled(liveLongDuration, motionPressReference)
    readonly property int motionGeometry: scaled(liveLongDuration, motionGeometryReference)
    readonly property int motionEmphasis: scaled(liveLongDuration, motionEmphasisReference)
    readonly property int motionPage: scaled(liveLongDuration, motionPageReference)
    readonly property int motionPortal: scaled(liveLongDuration, motionPortalReference)

    Component.onCompleted: {
        try {
            core.motionProbe = Qt.createQmlObject(
                'import QtQuick; import org.kde.kirigami as Kirigami; QtObject { readonly property int longDuration: Kirigami.Units.longDuration }',
                core, 'MoOSMotionSpeed')
        } catch (error) {
            core.motionProbe = null
        }
    }

    // border
    readonly property int borderHairline: 1
    readonly property int focusWidth: 2
    readonly property int focusGap: 3

    // icon
    readonly property int iconSmall: 16
    readonly property int iconControl: 20
    readonly property int iconLarge: 24
    readonly property int iconHero: 32

    // layout
    readonly property int panelHeight: 54
    readonly property int dialogWidth: 792
    readonly property int dialogHeight: 576
    readonly property int dialogCompactWidth: 560
    readonly property int sidebarCompactWidth: 76
    readonly property int sidebarExpandedWidth: 188
    readonly property int breakpointExpanded: 1120
    readonly property int commandCenterWidth: 1360
    readonly property int commandCenterHeight: 860
    readonly property int commandCenterMinimumWidth: 1040
    readonly property int commandCenterMinimumHeight: 680
    readonly property int commandCenterSidebarWidth: 252
    readonly property int commandCenterHeroHeight: 312
    readonly property int desktopHubColumns: 46
    readonly property int desktopHubRows: 14
    readonly property int desktopHubClockColumns: 12
    readonly property int desktopHubWeatherColumns: 17
    readonly property int desktopHubSystemColumns: 14

    // font
    readonly property string interfaceFamily: "IBM Plex Sans Arabic"
    readonly property string monospaceFamily: "JetBrains Mono"

    // opacity
    readonly property real surfaceRestingOpacity: 0.11
    readonly property real surfaceHoverOpacity: 0.24
    readonly property real surfacePressedOpacity: 0.34
    readonly property real glassRestingOpacity: 0.22
    readonly property real glassHoverOpacity: 0.25
    readonly property real glassSelectedOpacity: 0.4
    readonly property real glassBorderOpacity: 0.22
    readonly property real floatingGlassOpacity: 0.82
    readonly property real disabledOpacity: 0.48
    readonly property real mutedOpacity: 0.66
    readonly property real focusOpacity: 0.6
    readonly property real sessionGlassOpacity: 0.58
    readonly property real sessionScrimTopOpacity: 0.52
    readonly property real sessionScrimMidOpacity: 0.3
    readonly property real sessionScrimBottomOpacity: 0.6
    readonly property real destructiveBorderOpacity: 0.52
    readonly property real destructiveHoverBorderOpacity: 0.82

    // material
    readonly property int blurCeiling: 15
    readonly property int shadowBlur: 15
    readonly property int shadowYOffset: 8
    readonly property real pressScale: 0.97
    readonly property real hoverScale: 1.02
    readonly property real springStiffness: 4
    readonly property real springDamping: 0.32
    readonly property real springEpsilon: 0.005

    // easing
    readonly property int easeStandard: Easing.OutCubic
    readonly property int easeEmphasis: Easing.OutQuart
    readonly property int easeSpring: Easing.OutBack

    function typeSize(requested, scale) {
        const role = requested <= typeCaption ? typeCaption
                   : requested <= typeSecondary ? typeSecondary
                   : requested <= typeBody ? typeBody
                   : requested <= 17 ? typeLabel
                   : requested <= 22 ? typeTitle
                   : requested <= 28 ? typeHeadline
                   : requested <= 40 ? typeDisplay : typeHero
        return Math.round(role * Math.max(0.75, scale || 1))
    }

    function duration(enabled, role) {
        return enabled ? role : 0
    }

    // The same motion role, at the speed the OWNER asked for.
    //
    // Plasma has exactly one animation-speed control, [KDE]
    // AnimationDurationFactor in kdeglobals, and moos-visual-tier writes it
    // per hardware tier (flagship 1, balanced 0.85, essential 0.4). It reaches
    // QML only through Kirigami.Units.longDuration, which the Kirigami platform
    // plugins compute from it: measured in tests/test_moos_motion_gate.py on a
    // real Qt runtime as 200 at factor 1, 100 at 0.5, and floored to 1 at 0.
    //
    // duration() above answers that question only as yes-or-no, so on a tier
    // where Plasma runs at 40% the MoOS surfaces still ran at 100% and the shell
    // and the apps were visibly out of rhythm. This scales a role by the same
    // one control, and still returns 0 - not a fast animation - when the owner
    // has turned animations off.
    //
    // The live longDuration is PASSED IN rather than read here on purpose:
    // this singleton is loaded by the session splash and the login greeter as
    // well as by the shell, and it must not acquire an import that has to be
    // resolvable in every one of those engines.
    function scaled(longDuration, role) {
        if (longDuration <= 1) { return 0 }
        return Math.max(1, Math.round(role * longDuration / 200))
    }

    function isLight(color) {
        return color.hslLightness > 0.55
    }

    function stateOpacity(enabled, hovered, pressed, selected) {
        if (!enabled) return 0
        if (pressed) return surfacePressedOpacity
        if (selected) return glassSelectedOpacity
        return hovered ? surfaceHoverOpacity : surfaceRestingOpacity
    }

    // How dense the Liquid Glass is, DERIVED from the palette it
    // sits on.
    //
    // Every shell surface used to hardcode its own alpha - 0.72 in
    // the media capsule, 0.84 when light, 0.72 again in the hero
    // clock - so glass density lived in QML constants that no theme
    // package could reach. That is the real reason the sixteen
    // families looked structurally identical: only their hue could
    // ever change. Measuring proved it the hard way, when varying
    // KWin's blur noise per family moved exactly zero pixels: KWin
    // governs what shows THROUGH a translucent window, never an
    // alpha we paint ourselves.
    //
    //   near-black (Midnight .043, Arena .090, Scholar .096)  0.86
    //       denser, so true black stays true black and the slab
    //       reads as one surface
    //   dark  (Graphite .137, Nova, Amethyst, Aurora, Forge)  0.72
    //       the reference finish the system was tuned against
    //   light (every *Light profile, .82-.88)  0.80 - a pale
    //       surface over a pale wallpaper needs more body to hold
    //       its edge
    //
    // Thresholds were set from the SHIPPED palettes, not guessed:
    // measured across all sixteen colour schemes they select three
    // distinct densities and leave the default exactly where it was.
    function glassDensity(background) {
        const l = background.hslLightness
        if (l <= 0.10) { return 0.86 }
        if (isLight(background)) { return 0.80 }
        return 0.72
    }

    // ── Aurora Glass: one material, four depths ────────────────────────
    //
    // Glass on its own is a flat pane. What makes a stack of surfaces read
    // as DEPTH is the pair of edges every real piece of glass has: a darker
    // rim where it meets what is behind it, and a brighter line along the
    // edge the light falls on. Apple added exactly that to Liquid Glass in
    // iOS/macOS 27 after a year of flat translucency, and the reason is
    // measurable rather than fashionable: a surface with a rim and a
    // highlight separates from its background at every wallpaper, while an
    // alpha-only surface disappears over a busy photograph.
    //
    // MoOS derives all three from the palette it is already wearing, so a
    // family changes personality without any surface hardcoding a colour:
    //
    //   glassLevelScene    the desktop's own cards, closest to the wallpaper
    //   glassLevelPanel    the bar, the Island capsule, the search button
    //   glassLevelPopover  menus, MoOS Search, the switcher
    //   glassLevelDialog   questions and sheets, the furthest forward
    //
    // Each level is denser than the one behind it, so a popover over the bar
    // over the desk reads as three sheets, not one soup.
    readonly property int glassLevelScene: 0
    readonly property int glassLevelPanel: 1
    readonly property int glassLevelPopover: 2
    readonly property int glassLevelDialog: 3

    function glassDensityAt(background, level) {
        const base = glassDensity(background)
        const step = isLight(background) ? 0.045 : 0.055
        return Math.min(0.97, base + step * Math.max(0, level))
    }

    // The rim: darker than the surface on a light palette, darker still on a
    // dark one, and never a pure black line — a hairline of the palette's own
    // shadow. Strength grows with depth, because a surface further forward
    // sits above more of the scene.
    function glassEdge(background, level) {
        const weight = (isLight(background) ? 0.10 : 0.22)
                     + 0.03 * Math.max(0, level)
        return Qt.rgba(0, 0, 0, Math.min(0.42, weight))
    }

    // The specular: one bright line along the top edge, the width of a
    // hairline, stronger on light palettes where the rim alone is subtle.
    // This is the only place MoOS paints white.
    function glassSpecular(background, level) {
        const weight = (isLight(background) ? 0.55 : 0.30)
                     - 0.05 * Math.max(0, level)
        return Qt.rgba(1, 1, 1, Math.max(0.12, weight))
    }
}
