pragma Singleton
import QtQuick

// Generated by artwork/generate_moos_design_core.py.
// Edit artwork/moos-design/tokens.json, never this file.
QtObject {
    // spacing
    readonly property int space1: 4
    readonly property int space2: 8
    readonly property int space3: 12
    readonly property int space4: 16
    readonly property int space5: 24
    readonly property int space6: 32
    readonly property int space7: 40
    readonly property int space8: 48

    // radius
    readonly property int radiusSmall: 8
    readonly property int radiusControl: 12
    readonly property int radiusCard: 16
    readonly property int radiusPanel: 24
    readonly property int radiusDialog: 28
    readonly property int radiusPill: 999

    // target
    readonly property int targetCompact: 40
    readonly property int targetControl: 44
    readonly property int targetComfortable: 48

    // type
    readonly property int typeCaption: 11
    readonly property int typeSecondary: 13
    readonly property int typeBody: 14
    readonly property int typeLabel: 15
    readonly property int typeTitle: 20
    readonly property int typeHeadline: 24
    readonly property int typeDisplay: 32
    readonly property int typeHero: 48

    // weight
    readonly property int weightRegular: 400
    readonly property int weightMedium: 500
    readonly property int weightDemiBold: 600
    readonly property int weightBold: 700

    // motion
    readonly property int motionFast: 120
    readonly property int motionPress: 160
    readonly property int motionGeometry: 220
    readonly property int motionEmphasis: 260
    readonly property int motionPage: 320
    readonly property int motionPortal: 460

    // border
    readonly property int borderHairline: 1
    readonly property int focusWidth: 2
    readonly property int focusGap: 3

    // icon
    readonly property int iconSmall: 16
    readonly property int iconControl: 20
    readonly property int iconLarge: 24
    readonly property int iconHero: 32

    // layout
    readonly property int panelHeight: 54
    readonly property int dialogWidth: 792
    readonly property int dialogHeight: 576
    readonly property int dialogCompactWidth: 560
    readonly property int sidebarCompactWidth: 76
    readonly property int sidebarExpandedWidth: 188
    readonly property int breakpointExpanded: 1120
    readonly property int commandCenterWidth: 1360
    readonly property int commandCenterHeight: 860
    readonly property int commandCenterMinimumWidth: 1040
    readonly property int commandCenterMinimumHeight: 680
    readonly property int commandCenterSidebarWidth: 252
    readonly property int commandCenterHeroHeight: 312
    readonly property int desktopHubColumns: 46
    readonly property int desktopHubRows: 14
    readonly property int desktopHubClockColumns: 12
    readonly property int desktopHubWeatherColumns: 17
    readonly property int desktopHubSystemColumns: 14

    // font
    readonly property string interfaceFamily: "IBM Plex Sans Arabic"
    readonly property string monospaceFamily: "JetBrains Mono"

    // opacity
    readonly property real surfaceRestingOpacity: 0.11
    readonly property real surfaceHoverOpacity: 0.24
    readonly property real surfacePressedOpacity: 0.34
    readonly property real glassRestingOpacity: 0.22
    readonly property real glassHoverOpacity: 0.25
    readonly property real glassSelectedOpacity: 0.4
    readonly property real glassBorderOpacity: 0.22
    readonly property real floatingGlassOpacity: 0.82
    readonly property real disabledOpacity: 0.48
    readonly property real mutedOpacity: 0.66
    readonly property real focusOpacity: 0.6
    readonly property real sessionGlassOpacity: 0.58
    readonly property real sessionScrimTopOpacity: 0.52
    readonly property real sessionScrimMidOpacity: 0.3
    readonly property real sessionScrimBottomOpacity: 0.6
    readonly property real destructiveBorderOpacity: 0.52
    readonly property real destructiveHoverBorderOpacity: 0.82

    // material
    readonly property int blurCeiling: 15
    readonly property int shadowBlur: 15
    readonly property int shadowYOffset: 8
    readonly property real pressScale: 0.97
    readonly property real hoverScale: 1.02

    // easing
    readonly property int easeStandard: Easing.OutCubic
    readonly property int easeEmphasis: Easing.OutQuart
    readonly property int easeSpring: Easing.OutBack

    function typeSize(requested, scale) {
        const role = requested <= typeCaption ? typeCaption
                   : requested <= typeSecondary ? typeSecondary
                   : requested <= typeBody ? typeBody
                   : requested <= 17 ? typeLabel
                   : requested <= 22 ? typeTitle
                   : requested <= 28 ? typeHeadline
                   : requested <= 40 ? typeDisplay : typeHero
        return Math.round(role * Math.max(0.75, scale || 1))
    }

    function duration(enabled, role) {
        return enabled ? role : 0
    }

    function isLight(color) {
        return color.hslLightness > 0.55
    }

    function stateOpacity(enabled, hovered, pressed, selected) {
        if (!enabled) return 0
        if (pressed) return surfacePressedOpacity
        if (selected) return glassSelectedOpacity
        return hovered ? surfaceHoverOpacity : surfaceRestingOpacity
    }
}
