#!/usr/bin/env python3
"""Release gates for MoOS-owned application artwork.

The interface symbols have a monochrome runtime contract; application marks
have a different job: stay individually recognisable in a 16 px dock cell while
sharing one optical plate, and carry the ACTIVE MoOS palette rather than one
frozen teal.

MoOS pins ``FollowsColorScheme=false`` on every icon theme (PROJECT_STATE.md
records why: with ``true``, KIconLoader re-colours from the *application*
palette and painted near-invisible symbols on the live dark Launcher).  So the
palette is not followed at runtime — it is **baked**, once per palette icon
theme.  That makes "the icons change with the theme" a property of the files on
disk, which is exactly the kind of claim a gate can prove.  These checks prove
it, plus the two boundaries that have regressed silently before:

* the family generator must delegate Mo AI to its byte-exact commissioned
  artwork generator instead of overwriting it;
* MoPlayer must carry its ember-M cinema identity, not a generic play triangle.
"""

from __future__ import annotations

import collections
import importlib.util
import pathlib
import re
import unittest
import xml.etree.ElementTree as ElementTree

from PIL import Image


ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "artwork/generate_moos_app_icons.py"
BUILD = ROOT / "build_files/build.sh"
SHARE = ROOT / "system_files/usr/share"
ICONS = SHARE / "icons/hicolor"
SCHEMES = SHARE / "color-schemes"
SIZES = (16, 22, 24, 32, 48, 64, 96, 128, 192, 256, 512)

# The 14 palette icon themes generated by artwork/generate_moos_themes.py, plus
# the two broad bases that build.sh assembles from Colloid at image build time
# (those two are gated inside build.sh itself — see recolor_moos_app_dir).
PALETTE_THEMES = (
    "MoOSUI2Amethyst", "MoOSUI2AmethystLight",
    "MoOSUI2Arena", "MoOSUI2ArenaLight",
    "MoOSUI2Aurora", "MoOSUI2AuroraLight",
    "MoOSUI2Daylight",
    "MoOSUI2Forge", "MoOSUI2ForgeLight",
    "MoOSUI2Midnight",
    "MoOSUI2Nova", "MoOSUI2NovaLight",
    "MoOSUI2Scholar", "MoOSUI2ScholarLight",
)

# KDE only guarantees legibility for these pairings, so the family only uses
# them: HighlightedText on Highlight, and the window foregrounds on the window
# background (used inverted here — semantic tile, background-coloured glyph).
ALLOWED_PAIRS = {
    ("Highlight", "HighlightedText"),
    ("PositiveText", "Background"),
    ("NeutralText", "Background"),
    ("NegativeText", "Background"),
    ("Text", "Background"),
}
MINIMUM_CONTRAST = 4.0

HEX = re.compile(r"#[0-9a-fA-F]{6}")
STYLE_ELEMENT = re.compile(
    r'<style id="current-color-scheme"[^>]*>(.*?)</style>', re.DOTALL
)
SVG_NS = "{http://www.w3.org/2000/svg}"


def load_generator():
    spec = importlib.util.spec_from_file_location("moos_app_icons", GENERATOR)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {GENERATOR}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


MODULE = load_generator()


def channels(colour: str) -> tuple[int, int, int]:
    value = colour.lstrip("#")
    return tuple(int(value[index:index + 2], 16) for index in (0, 2, 4))


def relative_luminance(colour: str) -> float:
    def linear(channel: int) -> float:
        fraction = channel / 255
        return fraction / 12.92 if fraction <= 0.03928 else ((fraction + 0.055) / 1.055) ** 2.4

    red, green, blue = (linear(channel) for channel in channels(colour))
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def contrast(first: str, second: str) -> float:
    lighter, darker = sorted(
        (relative_luminance(first), relative_luminance(second)), reverse=True
    )
    return (lighter + 0.05) / (darker + 0.05)


def all_palettes() -> dict[str, dict[str, str]]:
    return {
        scheme.stem: MODULE.palette_roles(scheme)
        for scheme in sorted(SCHEMES.glob("MoOSUI2*.colors"))
    }


def stylesheet_of(svg: str) -> dict[str, str]:
    match = STYLE_ELEMENT.search(svg)
    if match is None:
        raise AssertionError("mark has no current-color-scheme stylesheet")
    return dict(
        re.findall(r"\.ColorScheme-(\w+)\s*\{\s*color:\s*(#[0-9a-fA-F]{6})", match[1])
    )


class ProtectedIdentities(unittest.TestCase):
    def test_moai_is_not_authored_by_the_family_glyph_catalog(self) -> None:
        self.assertNotIn("moos-moai", MODULE.MARKS)
        self.assertEqual(
            MODULE.MOAI_GENERATOR.name,
            "generate_moai_icon.py",
            "the family generator must delegate the protected identity",
        )

    def test_moai_master_is_a_seated_orb_not_an_edge_to_edge_raster(self) -> None:
        # The seating wrapper leaves the tile margin transparent.  A flood-filled
        # corner means the family generator overwrote the commissioned artwork.
        with Image.open(ICONS / "512x512/apps/moos-moai.png") as source:
            raster = source.convert("RGBA")
        for corner in ((2, 2), (509, 2), (2, 509), (509, 509)):
            self.assertEqual(
                raster.getpixel(corner)[3], 0, f"Mo AI corner {corner} is not clear"
            )

    def test_moai_carries_the_same_optical_weight_as_its_tiled_siblings(self) -> None:
        # Mo AI is the one tile-less mark, so nothing in the markup makes it the
        # right size — only the seating numbers do, and shipping the raw master
        # once put a 949 px orb in a row of 880 px plates.  Measure it.
        orb = self._footprint("moos-moai")
        plate = self._footprint("moos-store")
        for axis, (orb_span, plate_span) in enumerate(zip(orb, plate)):
            with self.subTest(axis="width" if axis == 0 else "height"):
                self.assertLess(
                    abs(orb_span - plate_span) / plate_span,
                    0.02,
                    f"Mo AI spans {orb_span}px where the family plate spans "
                    f"{plate_span}px — it breaks the dock's size grid",
                )

    def _footprint(self, name: str) -> tuple[int, int]:
        with Image.open(ICONS / f"512x512/apps/{name}.png") as source:
            alpha = source.convert("RGBA").getchannel("A")
        box = alpha.point(lambda value: 255 if value > 40 else 0).getbbox()
        self.assertIsNotNone(box, f"{name} renders nothing at 512 px")
        return box[2] - box[0], box[3] - box[1]

    def test_moplayer_keeps_its_ember_m_identity(self) -> None:
        svg = (ICONS / "scalable/apps/moos-moplayer.svg").read_text(encoding="utf-8")
        self.assertIn("M275 654V334", svg, "the MoPlayer M geometry is gone")
        self.assertNotIn("<image", svg)
        self.assertNotIn("<text", svg)
        self.assertNotIn("m462 392 170 112-170 112", svg, "generic play triangle")


class MarkContract(unittest.TestCase):
    def test_committed_masters_are_what_the_generator_produces(self) -> None:
        for name, mark in MODULE.MARKS.items():
            with self.subTest(mark=name):
                master = ICONS / f"scalable/apps/{name}.svg"
                self.assertEqual(
                    master.read_text(encoding="utf-8"),
                    MODULE.icon_svg(name, mark),
                    f"{name}.svg is not what artwork/generate_moos_app_icons.py"
                    " generates — regenerate instead of hand-editing",
                )

    def test_every_mark_is_valid_xml_with_one_recolourable_stylesheet(self) -> None:
        for name in MODULE.MARKS:
            with self.subTest(mark=name):
                svg = (ICONS / f"scalable/apps/{name}.svg").read_text(encoding="utf-8")
                ElementTree.fromstring(svg)
                self.assertEqual(
                    svg.count('id="current-color-scheme"'),
                    1,
                    "exactly one stylesheet, or a bake replaces the wrong block",
                )
                self.assertEqual(
                    stylesheet_of(svg),
                    MODULE.FALLBACK_STYLESHEET,
                    "masters must carry the MoOS default palette",
                )

    def test_no_ink_is_a_literal_colour(self) -> None:
        # Every paint outside the stylesheet must be currentColor, none, or the
        # neutral white sheen: a literal palette hex in the geometry survives
        # every bake and pins one theme's accent onto all sixteen.
        for name in MODULE.MARKS:
            with self.subTest(mark=name):
                svg = (ICONS / f"scalable/apps/{name}.svg").read_text(encoding="utf-8")
                geometry = STYLE_ELEMENT.sub("", svg)
                self.assertEqual(
                    {found.lower() for found in HEX.findall(geometry)} - {"#ffffff"},
                    set(),
                    "hardcoded colour in the geometry",
                )
                for element in ElementTree.fromstring(svg).iter():
                    for attribute in ("fill", "stroke"):
                        paint = element.get(attribute)
                        if paint is None:
                            continue
                        self.assertTrue(
                            paint in {"currentColor", "none"}
                            or paint.startswith("url(#"),
                            f"{element.tag} {attribute}={paint}",
                        )

    def test_every_paint_resolves_to_a_colour_role(self) -> None:
        # currentColor is only meaningful if some ancestor sets a ColorScheme-*
        # class.  An unclassed currentColor paints black on every palette.
        for name in MODULE.MARKS:
            with self.subTest(mark=name):
                tree = ElementTree.fromstring(
                    (ICONS / f"scalable/apps/{name}.svg").read_text(encoding="utf-8")
                )
                self.assertTrue(self._roles_cover_every_paint(tree, role=None))

    def _roles_cover_every_paint(self, element, role: str | None) -> bool:
        classes = element.get("class", "")
        for token in classes.split():
            if token.startswith("ColorScheme-"):
                role = token
        paints = {element.get("fill"), element.get("stroke")}
        if "currentColor" in paints:
            self.assertIsNotNone(
                role, f"{element.tag} uses currentColor with no colour role"
            )
        for child in element:
            self._roles_cover_every_paint(child, role)
        return True

    def test_tile_and_glyph_use_a_pairing_kde_guarantees(self) -> None:
        for name, mark in MODULE.MARKS.items():
            with self.subTest(mark=name):
                self.assertIn((mark["tile"], mark["ink"]), ALLOWED_PAIRS)

    def test_every_pairing_clears_wcag_on_all_sixteen_palettes(self) -> None:
        worst = (99.0, "", "")
        for palette_name, roles in all_palettes().items():
            for name, mark in MODULE.MARKS.items():
                ratio = contrast(roles[mark["tile"]], roles[mark["ink"]])
                with self.subTest(palette=palette_name, mark=name):
                    self.assertGreaterEqual(
                        ratio,
                        MINIMUM_CONTRAST,
                        f"{name} on {palette_name} is {ratio:.2f}:1",
                    )
                worst = min(worst, (ratio, name, palette_name))
        self.assertGreaterEqual(worst[0], MINIMUM_CONTRAST)


class RasterLadder(unittest.TestCase):
    def test_every_mark_exports_the_full_ladder(self) -> None:
        for name in ("moos-moai", *MODULE.MARKS):
            for size in SIZES:
                with self.subTest(mark=name, size=size):
                    raster = ICONS / f"{size}x{size}/apps/{name}.png"
                    self.assertTrue(raster.is_file(), f"missing {raster}")
                    with Image.open(raster) as image:
                        self.assertEqual(max(image.size), size)

    def test_the_dock_cell_shows_a_tile_and_a_glyph(self) -> None:
        # The failure this catches is a mark that rasterises to a blank plate
        # (glyph lost) or to almost nothing (geometry collapsed): both look like
        # a real icon in a file listing and like a bug on the dock.
        for name in MODULE.MARKS:
            with self.subTest(mark=name):
                with Image.open(ICONS / f"16x16/apps/{name}.png") as source:
                    image = source.convert("RGBA")
                    pixels = [
                        image.getpixel((x, y))
                        for y in range(image.height)
                        for x in range(image.width)
                    ]
                opaque = [pixel for pixel in pixels if pixel[3] > 200]
                self.assertGreater(
                    len(opaque) / len(pixels), 0.5, "tile does not fill the cell"
                )
                tally = collections.Counter(pixel[:3] for pixel in opaque)
                tile = "#%02x%02x%02x" % tally.most_common(1)[0][0]
                glyph = [
                    pixel for pixel in opaque
                    if contrast("#%02x%02x%02x" % pixel[:3], tile) > 2.0
                ]
                self.assertGreater(
                    len(glyph) / len(opaque),
                    0.04,
                    "no glyph survives the 16 px cell",
                )

    def test_compatibility_copies_track_their_source(self) -> None:
        for size in SIZES:
            with self.subTest(size=size):
                self.assertEqual(
                    (ICONS / f"{size}x{size}/apps/mo-store.png").read_bytes(),
                    (ICONS / f"{size}x{size}/apps/moos-store.png").read_bytes(),
                )
        self.assertEqual(
            (ROOT / "moremote/Logo.png").read_bytes(),
            (ICONS / "512x512/apps/moos-pc-remote.png").read_bytes(),
        )


class PaletteBaking(unittest.TestCase):
    """The actual "icons follow the theme" gate."""

    def test_each_palette_theme_ships_the_whole_family_baked_from_its_own_palette(self) -> None:
        for theme in PALETTE_THEMES:
            roles = MODULE.palette_roles(SCHEMES / f"{theme}.colors")
            apps = SHARE / f"icons/{theme}/moos/apps/scalable"
            with self.subTest(theme=theme):
                self.assertTrue(apps.is_dir(), f"{theme} has no application marks")
                self.assertEqual(
                    {path.stem for path in apps.glob("moos-*.svg")},
                    set(MODULE.MARKS),
                    f"{theme} application-mark inventory is incomplete",
                )
                for name in MODULE.MARKS:
                    baked = stylesheet_of((apps / f"{name}.svg").read_text("utf-8"))
                    self.assertEqual(
                        {role: value.lower() for role, value in baked.items()},
                        {role: value.lower() for role, value in roles.items()},
                        f"{theme}/{name} is not baked from {theme}.colors",
                    )

    def test_a_palette_theme_actually_differs_from_the_default(self) -> None:
        # Inventory and structure can be perfect while every overlay holds the
        # same default teal — which is what "the icons do not follow the theme"
        # looked like the last time.
        default = MODULE.FALLBACK_STYLESHEET["Highlight"].lower()
        for theme in PALETTE_THEMES:
            svg = (SHARE / f"icons/{theme}/moos/apps/scalable/moos-store.svg").read_text(
                encoding="utf-8"
            )
            with self.subTest(theme=theme):
                self.assertNotEqual(
                    stylesheet_of(svg)["Highlight"].lower(),
                    default,
                    f"{theme} still carries the default accent",
                )

    def test_palette_themes_declare_the_application_overlay(self) -> None:
        for theme in PALETTE_THEMES:
            index = (SHARE / f"icons/{theme}/index.theme").read_text(encoding="utf-8")
            with self.subTest(theme=theme):
                self.assertIn(
                    "Directories=moos/actions/scalable,moos/apps/scalable", index
                )
                self.assertIn("[moos/apps/scalable]", index)
                self.assertIn("Context=Applications", index)
                self.assertIn("FollowsColorScheme=false", index)

    def test_the_two_broad_bases_bake_from_the_same_numbers(self) -> None:
        # build.sh cannot import the generator, so its sed pattern repeats these
        # hexes.  If the master default ever moves, that copy goes stale and the
        # light base silently keeps dark inks — so compare them here.
        build = BUILD.read_text(encoding="utf-8")
        source = re.search(
            r"recolor_moos_app_dir\(\) \{.*?\n\}", build, re.DOTALL
        )
        self.assertIsNotNone(source, "build.sh no longer bakes application marks")
        found = [hex_value.lower() for hex_value in HEX.findall(source[0])]
        self.assertEqual(
            found,
            [
                MODULE.FALLBACK_STYLESHEET[role].lower()
                for role in (
                    "Text", "Background", "Highlight", "HighlightedText",
                    "PositiveText", "NeutralText", "NegativeText",
                )
            ],
            "build.sh substitutes hexes the masters no longer contain",
        )
        for theme, scheme in (("MoOSUI2", "MoOSUI2Dark"), ("MoOSUI2Light", "MoOSUI2Light")):
            roles = MODULE.palette_roles(SCHEMES / f"{scheme}.colors")
            call = re.search(
                rf"recolor_moos_app_dir \\\n\s+/usr/share/icons/{theme}/moos/apps/scalable"
                r" \\\n\s+([^\n]+)",
                build,
            )
            with self.subTest(theme=theme):
                self.assertIsNotNone(call, f"{theme} marks are never re-inked")
                self.assertEqual(
                    [value.lower() for value in HEX.findall(call[1])],
                    [
                        roles[role].lower()
                        for role in (
                            "Text", "Background", "Highlight", "HighlightedText",
                            "PositiveText", "NeutralText", "NegativeText",
                        )
                    ],
                    f"{theme} is not baked from {scheme}.colors",
                )


class ThemeSwitchIsVisible(unittest.TestCase):
    def test_the_review_evidence_covers_light_and_dark_palettes(self) -> None:
        preview = ROOT / "artwork/moos-ui2/previews/moos-app-icons-palettes.png"
        self.assertTrue(preview.is_file(), "no rendered palette evidence")
        self.assertGreaterEqual(len(MODULE.PREVIEW_PALETTES), 4)
        luminances = {
            name: relative_luminance(
                MODULE.palette_roles(SCHEMES / f"{name}.colors")["Background"]
            )
            for name in MODULE.PREVIEW_PALETTES
        }
        self.assertTrue(
            any(value > 0.5 for value in luminances.values()),
            "palette evidence never shows a light palette",
        )
        self.assertTrue(
            any(value < 0.1 for value in luminances.values()),
            "palette evidence never shows a dark palette",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
