#!/usr/bin/env python3
"""Generate the globally importable MoOS Design Core QML token singleton.

`artwork/moos-design/tokens.json` is the metric/state source of truth. Palette
colour continues to come from Kirigami's semantic roles, which are generated
from the separate MoOS profile palette source. Keeping these responsibilities
separate means a profile changes personality without changing UX geometry.
"""

from __future__ import annotations

import json
import os
from pathlib import Path


TEST_ROOT = os.environ.get("MOOS_DESIGN_TEST_ROOT")
ROOT = Path(TEST_ROOT).resolve() if TEST_ROOT else Path(__file__).resolve().parents[1]
SOURCE = ROOT / "artwork/moos-design/tokens.json"
OUTPUT = ROOT / "system_files/usr/lib64/qt6/qml/org/moos/ui"


def load_tokens() -> dict:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if document.get("schema") != 1:
        raise SystemExit("MoOS Design Core: unsupported token schema")

    required = {
        "spacing", "radius", "target", "type", "font", "weight", "motion",
        "opacity", "border", "icon", "layout", "material", "easing",
    }
    missing = required.difference(document)
    if missing:
        raise SystemExit(f"MoOS Design Core: missing groups: {sorted(missing)}")

    blur = document["material"].get("blurCeiling")
    shadow = document["material"].get("shadowBlur")
    if not isinstance(blur, int) or not 0 <= blur <= 15:
        raise SystemExit("MoOS Design Core: blurCeiling must be 0..15")
    if not isinstance(shadow, int) or not 0 <= shadow <= 15:
        raise SystemExit("MoOS Design Core: shadowBlur must be 0..15")

    for name, value in document["opacity"].items():
        if not isinstance(value, (int, float)) or not 0 <= value <= 1:
            raise SystemExit(f"MoOS Design Core: {name} must be 0..1")
    return document


def qml_number(value: int | float) -> str:
    if isinstance(value, int):
        return str(value)
    return f"{value:.3f}".rstrip("0").rstrip(".")


def render_tokens(document: dict) -> str:
    lines = [
        "pragma Singleton",
        "import QtQuick",
        "",
        "// Generated by artwork/generate_moos_design_core.py.",
        "// Edit artwork/moos-design/tokens.json, never this file.",
        "QtObject {",
    ]
    integer_groups = (
        "spacing", "radius", "target", "type", "weight", "motion",
        "border", "icon", "layout",
    )
    for group in integer_groups:
        lines.append(f"    // {group}")
        for name, value in document[group].items():
            lines.append(f"    readonly property int {name}: {qml_number(value)}")
        lines.append("")

    lines.append("    // font")
    for name, value in document["font"].items():
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"MoOS Design Core: invalid font {name}")
        lines.append(
            f"    readonly property string {name}: "
            f"{json.dumps(value, ensure_ascii=False)}"
        )
    lines.append("")

    lines.append("    // opacity")
    for name, value in document["opacity"].items():
        lines.append(f"    readonly property real {name}: {qml_number(value)}")
    lines.append("")

    lines.append("    // material")
    for name, value in document["material"].items():
        kind = "int" if isinstance(value, int) else "real"
        lines.append(f"    readonly property {kind} {name}: {qml_number(value)}")
    lines.append("")

    lines.append("    // easing")
    for name, value in document["easing"].items():
        if not isinstance(value, str) or not value.startswith("Easing."):
            raise SystemExit(f"MoOS Design Core: invalid easing {name}")
        lines.append(f"    readonly property int {name}: {value}")
    lines.extend([
        "",
        "    function typeSize(requested, scale) {",
        "        const role = requested <= typeCaption ? typeCaption",
        "                   : requested <= typeSecondary ? typeSecondary",
        "                   : requested <= typeBody ? typeBody",
        "                   : requested <= 17 ? typeLabel",
        "                   : requested <= 22 ? typeTitle",
        "                   : requested <= 28 ? typeHeadline",
        "                   : requested <= 40 ? typeDisplay : typeHero",
        "        return Math.round(role * Math.max(0.75, scale || 1))",
        "    }",
        "",
        "    function duration(enabled, role) {",
        "        return enabled ? role : 0",
        "    }",
        "",
        "    function isLight(color) {",
        "        return color.hslLightness > 0.55",
        "    }",
        "",
        "    function stateOpacity(enabled, hovered, pressed, selected) {",
        "        if (!enabled) return 0",
        "        if (pressed) return surfacePressedOpacity",
        "        if (selected) return glassSelectedOpacity",
        "        return hovered ? surfaceHoverOpacity : surfaceRestingOpacity",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_qmldir() -> str:
    return """module org.moos.ui
singleton Tokens 1.0 Tokens.qml
KeyboardViewport 1.0 KeyboardViewport.js
SymbolCatalog 1.0 SymbolCatalog.js
Surface 1.0 Surface.qml
GlassSurface 1.0 GlassSurface.qml
Card 1.0 Card.qml
Button 1.0 Button.qml
IconButton 1.0 IconButton.qml
Separator 1.0 Separator.qml
FocusRing 1.0 FocusRing.qml
SymbolIcon 1.0 SymbolIcon.qml
"""


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main() -> None:
    document = load_tokens()
    write_if_changed(OUTPUT / "Tokens.qml", render_tokens(document))
    write_if_changed(OUTPUT / "qmldir", render_qmldir())
    print(f"MoOS Design Core generated at {OUTPUT}")


if __name__ == "__main__":
    main()
