#!/usr/bin/env python3
"""Generate the globally importable MoOS Design Core QML token singleton.

`artwork/moos-design/tokens.json` is the metric/state source of truth. Palette
colour continues to come from Kirigami's semantic roles, which are generated
from the separate MoOS profile palette source. Keeping these responsibilities
separate means a profile changes personality without changing UX geometry.
"""

from __future__ import annotations

import json
import os
from pathlib import Path


TEST_ROOT = os.environ.get("MOOS_DESIGN_TEST_ROOT")
ROOT = Path(TEST_ROOT).resolve() if TEST_ROOT else Path(__file__).resolve().parents[1]
SOURCE = ROOT / "artwork/moos-design/tokens.json"
OUTPUT = ROOT / "system_files/usr/lib64/qt6/qml/org/moos/ui"


def load_tokens() -> dict:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    if document.get("schema") != 1:
        raise SystemExit("MoOS Design Core: unsupported token schema")

    required = {
        "spacing", "radius", "target", "type", "font", "weight", "motion",
        "opacity", "border", "icon", "layout", "material", "easing",
    }
    missing = required.difference(document)
    if missing:
        raise SystemExit(f"MoOS Design Core: missing groups: {sorted(missing)}")

    blur = document["material"].get("blurCeiling")
    shadow = document["material"].get("shadowBlur")
    if not isinstance(blur, int) or not 0 <= blur <= 15:
        raise SystemExit("MoOS Design Core: blurCeiling must be 0..15")
    if not isinstance(shadow, int) or not 0 <= shadow <= 15:
        raise SystemExit("MoOS Design Core: shadowBlur must be 0..15")

    for name, value in document["opacity"].items():
        if not isinstance(value, (int, float)) or not 0 <= value <= 1:
            raise SystemExit(f"MoOS Design Core: {name} must be 0..1")
    return document


def qml_number(value: int | float) -> str:
    if isinstance(value, int):
        return str(value)
    return f"{value:.3f}".rstrip("0").rstrip(".")


def render_motion(motion: dict) -> list[str]:
    """The motion roles, at the speed the owner asked for.

    W7 gave `scaled()` to the four surfaces that call it by hand, and the station
    review of 2026-09-17 found the rest of MoOS still running at full speed on a
    tier where Plasma was at 40%: 288 places across the apps, the greeter and the
    plasmoids read a role directly, as `win.motionEnabled ? design.motionFast : 0`.
    Rewriting all of them would put the same expression in 288 places and leave the
    next surface free to forget again, so the ROLE itself now carries the speed:
    every one of those places scales without changing a line.

    `<name>Reference` keeps the designed duration at factor 1, for anything that
    needs the unscaled number (the gates compare against it).
    """
    lines = ["    // motion — the designed durations, at factor 1"]
    for name, value in motion.items():
        lines.append(f"    readonly property int {name}Reference: {qml_number(value)}")
    lines.extend([
        "",
        "    // The one animation-speed control, reaching every MoOS surface.",
        "    //",
        "    // Kirigami computes Units.longDuration from [KDE] AnimationDurationFactor,",
        "    // which moos-visual-tier writes per hardware tier and the owner can change;",
        "    // it is 200 at factor 1 and floored to 1 with animations off. This singleton",
        "    // must not IMPORT Kirigami — the session splash and the login greeter load it",
        "    // in engines where that import need not resolve — so it asks for the value at",
        "    // run time and keeps the designed speed when the answer is unavailable.",
        "    property QtObject motionProbe: null",
        "    readonly property int liveLongDuration: motionProbe ? motionProbe.longDuration : 200",
        "",
        "    // motion — what surfaces read; 0 when the owner has animations off",
        *(f"    readonly property int {name}: scaled(liveLongDuration, {name}Reference)"
          for name in motion),
        "",
        "    Component.onCompleted: {",
        "        try {",
        "            core.motionProbe = Qt.createQmlObject(",
        "                'import QtQuick; import org.kde.kirigami as Kirigami; "
        "QtObject { readonly property int longDuration: Kirigami.Units.longDuration }',",
        "                core, 'MoOSMotionSpeed')",
        "        } catch (error) {",
        "            core.motionProbe = null",
        "        }",
        "    }",
        "",
    ])
    return lines


def render_tokens(document: dict) -> str:
    lines = [
        "pragma Singleton",
        "import QtQuick",
        "import Qt.labs.platform",
        "import Qt.labs.settings",
        "",
        "// Generated by artwork/generate_moos_design_core.py.",
        "// Edit artwork/moos-design/tokens.json, never this file.",
        "QtObject {",
        "    id: core",
        "",
    ]
    integer_groups = (
        "spacing", "radius", "target", "type", "weight", "motion",
        "border", "icon", "layout",
    )
    for group in integer_groups:
        if group == "motion":
            lines.extend(render_motion(document["motion"]))
            continue
        lines.append(f"    // {group}")
        for name, value in document[group].items():
            lines.append(f"    readonly property int {name}: {qml_number(value)}")
        lines.append("")

    lines.append("    // font")
    for name, value in document["font"].items():
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"MoOS Design Core: invalid font {name}")
        lines.append(
            f"    readonly property string {name}: "
            f"{json.dumps(value, ensure_ascii=False)}"
        )
    lines.append("")

    lines.append("    // opacity")
    for name, value in document["opacity"].items():
        lines.append(f"    readonly property real {name}: {qml_number(value)}")
    lines.append("")

    lines.append("    // material")
    for name, value in document["material"].items():
        kind = "int" if isinstance(value, int) else "real"
        lines.append(f"    readonly property {kind} {name}: {qml_number(value)}")
    lines.append("")

    lines.append("    // easing")
    for name, value in document["easing"].items():
        if not isinstance(value, str) or not value.startswith("Easing."):
            raise SystemExit(f"MoOS Design Core: invalid easing {name}")
        lines.append(f"    readonly property int {name}: {value}")
    lines.extend([
        "",
        "    function typeSize(requested, scale) {",
        "        const role = requested <= typeCaption ? typeCaption",
        "                   : requested <= typeSecondary ? typeSecondary",
        "                   : requested <= typeBody ? typeBody",
        "                   : requested <= 17 ? typeLabel",
        "                   : requested <= 22 ? typeTitle",
        "                   : requested <= 28 ? typeHeadline",
        "                   : requested <= 40 ? typeDisplay : typeHero",
        "        return Math.round(role * Math.max(0.75, scale || 1))",
        "    }",
        "",
        "    function duration(enabled, role) {",
        "        return enabled ? role : 0",
        "    }",
        "",
        "    // The same motion role, at the speed the OWNER asked for.",
        "    //",
        "    // Plasma has exactly one animation-speed control, [KDE]",
        "    // AnimationDurationFactor in kdeglobals, and moos-visual-tier writes it",
        "    // per hardware tier (flagship 1, balanced 0.85, essential 0.4). It reaches",
        "    // QML only through Kirigami.Units.longDuration, which the Kirigami platform",
        "    // plugins compute from it: measured in tests/test_moos_motion_gate.py on a",
        "    // real Qt runtime as 200 at factor 1, 100 at 0.5, and floored to 1 at 0.",
        "    //",
        "    // duration() above answers that question only as yes-or-no, so on a tier",
        "    // where Plasma runs at 40% the MoOS surfaces still ran at 100% and the shell",
        "    // and the apps were visibly out of rhythm. This scales a role by the same",
        "    // one control, and still returns 0 - not a fast animation - when the owner",
        "    // has turned animations off.",
        "    //",
        "    // The live longDuration is PASSED IN rather than read here on purpose:",
        "    // this singleton is loaded by the session splash and the login greeter as",
        "    // well as by the shell, and it must not acquire an import that has to be",
        "    // resolvable in every one of those engines.",
        "    function scaled(longDuration, role) {",
        "        if (longDuration <= 1) { return 0 }",
        "        return Math.max(1, Math.round(role * longDuration / 200))",
        "    }",
        "",
        "    function isLight(color) {",
        "        return color.hslLightness > 0.55",
        "    }",
        "",
        "    function stateOpacity(enabled, hovered, pressed, selected) {",
        "        if (!enabled) return 0",
        "        if (pressed) return surfacePressedOpacity",
        "        if (selected) return glassSelectedOpacity",
        "        return hovered ? surfaceHoverOpacity : surfaceRestingOpacity",
        "    }",
        "",
        "    // How dense the Liquid Glass is, DERIVED from the palette it",
        "    // sits on.",
        "    //",
        "    // Every shell surface used to hardcode its own alpha - 0.72 in",
        "    // the media capsule, 0.84 when light, 0.72 again in the hero",
        "    // clock - so glass density lived in QML constants that no theme",
        "    // package could reach. That is the real reason the sixteen",
        "    // families looked structurally identical: only their hue could",
        "    // ever change. Measuring proved it the hard way, when varying",
        "    // KWin's blur noise per family moved exactly zero pixels: KWin",
        "    // governs what shows THROUGH a translucent window, never an",
        "    // alpha we paint ourselves.",
        "    //",
        "    //   near-black (Midnight .043, Arena .090, Scholar .096)  0.86",
        "    //       denser, so true black stays true black and the slab",
        "    //       reads as one surface",
        "    //   dark  (Graphite .137, Nova, Amethyst, Aurora, Forge)  0.72",
        "    //       the reference finish the system was tuned against",
        "    //   light (every *Light profile, .82-.88)  0.80 - a pale",
        "    //       surface over a pale wallpaper needs more body to hold",
        "    //       its edge",
        "    //",
        "    // Thresholds were set from the SHIPPED palettes, not guessed:",
        "    // measured across all sixteen colour schemes they select three",
        "    // distinct densities and leave the default exactly where it was.",
        "    function glassDensity(background) {",
        "        const l = background.hslLightness",
        "        if (l <= 0.10) { return 0.86 }",
        "        if (isLight(background)) { return 0.80 }",
        "        return 0.72",
        "    }",
        "",
        "    // ── Is there blur behind the glass? ────────────────────────────────",
        "    //",
        "    // Every density below assumes a blur pass behind the surface. Without",
        "    // one, 0.22 alpha over a wallpaper is not frosted glass — it is a",
        "    // window, and the text on it sits on whatever photograph is underneath.",
        "    // Measured on the A1 (llvmpipe, no blur): the surfaces were see-through",
        "    // and the review row is still open as P2.5.",
        "    //",
        "    // MoOS already decides this: moos-visual-tier turns blur OFF on the",
        "    // essential tier — software rendering, no render node, or a small",
        "    // machine — and writes kwinrc/Plugins/blurEnabled. So the surfaces read",
        "    // that same key, which also honours an owner who turned blur off",
        "    // themselves. Qt.labs.settings reads it synchronously at load; the",
        "    // default is true, matching /etc/xdg/kwinrc, so a machine with no user",
        "    // override behaves exactly as before.",
        "    property bool blurActive: clarity.blurEnabled",
        "    // writableLocation returns a URL (file:///…); QSettings wants a PATH.",
        "    // Handing it the URL made it open nothing, fall back to the default, and",
        "    // report blur as ON with blurEnabled=false sitting in the file — measured",
        "    // on a real engine before this line existed.",
        "    readonly property string clarityFile:",
        "        String(StandardPaths.writableLocation(StandardPaths.GenericConfigLocation))",
        "            .replace(/^file:\\/\\//, '') + '/kwinrc'",
        "    property var clarity: Settings {",
        "        fileName: core.clarityFile",
        "        category: 'Plugins'",
        "        property bool blurEnabled: true",
        "    }",
        "",
        "    // The fill a surface should actually paint. With blur behind it, the",
        "    // frosted density the palette asks for; without, opaque enough that the",
        "    // wallpaper stops competing with the text — the SAME colour, so nothing",
        "    // about the family changes, only how much of it there is.",
        "    function glassFill(background, level, resting) {",
        "        if (blurActive) { return resting }",
        "        return Math.max(resting, glassDensityAt(background, level))",
        "    }",
        "",
        "    // ── Aurora Glass: one material, four depths ────────────────────────",
        "    //",
        "    // Glass on its own is a flat pane. What makes a stack of surfaces read",
        "    // as DEPTH is the pair of edges every real piece of glass has: a darker",
        "    // rim where it meets what is behind it, and a brighter line along the",
        "    // edge the light falls on. Apple added exactly that to Liquid Glass in",
        "    // iOS/macOS 27 after a year of flat translucency, and the reason is",
        "    // measurable rather than fashionable: a surface with a rim and a",
        "    // highlight separates from its background at every wallpaper, while an",
        "    // alpha-only surface disappears over a busy photograph.",
        "    //",
        "    // MoOS derives all three from the palette it is already wearing, so a",
        "    // family changes personality without any surface hardcoding a colour:",
        "    //",
        "    //   glassLevelScene    the desktop's own cards, closest to the wallpaper",
        "    //   glassLevelPanel    the bar, the Island capsule, the search button",
        "    //   glassLevelPopover  menus, MoOS Search, the switcher",
        "    //   glassLevelDialog   questions and sheets, the furthest forward",
        "    //",
        "    // Each level is denser than the one behind it, so a popover over the bar",
        "    // over the desk reads as three sheets, not one soup.",
        "    readonly property int glassLevelScene: 0",
        "    readonly property int glassLevelPanel: 1",
        "    readonly property int glassLevelPopover: 2",
        "    readonly property int glassLevelDialog: 3",
        "",
        "    function glassDensityAt(background, level) {",
        "        const base = glassDensity(background)",
        "        const step = isLight(background) ? 0.045 : 0.055",
        "        return Math.min(0.97, base + step * Math.max(0, level))",
        "    }",
        "",
        "    // The rim: darker than the surface on a light palette, darker still on a",
        "    // dark one, and never a pure black line — a hairline of the palette's own",
        "    // shadow. Strength grows with depth, because a surface further forward",
        "    // sits above more of the scene.",
        "    function glassEdge(background, level) {",
        "        const weight = (isLight(background) ? 0.10 : 0.22)",
        "                     + 0.03 * Math.max(0, level)",
        "        return Qt.rgba(0, 0, 0, Math.min(0.42, weight))",
        "    }",
        "",
        "    // The specular: one bright line along the top edge, the width of a",
        "    // hairline, stronger on light palettes where the rim alone is subtle.",
        "    // This is the only place MoOS paints white.",
        "    function glassSpecular(background, level) {",
        "        const weight = (isLight(background) ? 0.55 : 0.30)",
        "                     - 0.05 * Math.max(0, level)",
        "        return Qt.rgba(1, 1, 1, Math.max(0.12, weight))",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def render_qmldir() -> str:
    return """module org.moos.ui
singleton Tokens 1.0 Tokens.qml
singleton Locale 1.0 Locale.qml
KeyboardViewport 1.0 KeyboardViewport.js
SymbolCatalog 1.0 SymbolCatalog.js
Surface 1.0 Surface.qml
GlassSurface 1.0 GlassSurface.qml
Card 1.0 Card.qml
Button 1.0 Button.qml
SpringFeedback 1.0 SpringFeedback.qml
IconButton 1.0 IconButton.qml
Separator 1.0 Separator.qml
FocusRing 1.0 FocusRing.qml
SymbolIcon 1.0 SymbolIcon.qml
"""


def render_locale() -> str:
    """The ONE answer to "what language is this session".

    Every first-party app had its own, and they disagreed. Measured on the live
    Arabic session (LANG=ar_SA.UTF-8, LANGUAGE=ar) with a QML probe through
    moos-qml-shell:

        Qt.locale().textDirection === Qt.RightToLeft      -> true
        Qt.application.layoutDirection === Qt.RightToLeft -> false

    Qt.application.layoutDirection follows the installed TRANSLATOR, not the
    locale. MoOS's QML apps carry their own bilingual strings instead of Qt
    translation catalogues, so no translator is ever installed and that property
    stays LeftToRight forever. Mo Settings used it and therefore rendered its
    entire interface in English on an Arabic-first operating system, while the
    launcher and the store — which read the locale — were correctly Arabic.

    Unlike Tokens, this is runtime state rather than a design constant, but it
    belongs in the same module for the same reason: one authority, imported by
    everyone, so the answer cannot drift apart again.
    """
    return """pragma Singleton
import QtQuick

// Generated by artwork/generate_moos_design_core.py.
// Edit the generator, never this file.
QtObject {
    // Read the LOCALE, never Qt.application.layoutDirection: the latter follows
    // an installed translator, and MoOS ships bilingual QML strings instead of
    // Qt translation catalogues, so it is LeftToRight on every MoOS session
    // including Arabic ones.
    readonly property bool rtl: Qt.locale().textDirection === Qt.RightToLeft
    readonly property string language: rtl ? "ar" : "en"

    // The one string helper. An app that writes its own `local()` is free to,
    // but it must take its direction from here.
    function local(ar, en) { return rtl ? ar : en }
}
"""


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main() -> None:
    document = load_tokens()
    write_if_changed(OUTPUT / "Tokens.qml", render_tokens(document))
    write_if_changed(OUTPUT / "Locale.qml", render_locale())
    write_if_changed(OUTPUT / "qmldir", render_qmldir())
    print(f"MoOS Design Core generated at {OUTPUT}")


if __name__ == "__main__":
    main()
